version: '3.9'
services:
  registry:
    image: registry:2
    ports:
    - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Realm
    volumes:
    - ./htpasswd:/auth/htpasswd
    - registry:/var/lib/registry
volumes:
  registry: